// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://izbuyhpftsehzwnhhjrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6YnV5aHBmdHNlaHp3bmhoanJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MjkyMzksImV4cCI6MjA3OTAwNTIzOX0.6-2RI7Zx1xnv6JBLmIlFB3y7PY0hkS4KMAj0fst0zeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);